# Cores prontas para usar no hyprland.conf (rgba com alpha embutido)
$active_border_1  = rgba(81d5ccff)
$active_border_2  = rgba(b0ccc8ff)
$inactive_border  = rgba(89939155)
$shadow_color     = rgba(00000080)
$shadow_inactive  = rgba(00000040)
