# Cores prontas para usar no hyprland.conf (rgba com alpha embutido)
$active_border_1  = rgba(80d4d5ff)
$active_border_2  = rgba(b0cccbff)
$inactive_border  = rgba(89939255)
$shadow_color     = rgba(00000080)
$shadow_inactive  = rgba(00000040)
