# Cores prontas para usar no hyprland.conf (rgba com alpha embutido)
$active_border_1  = rgba(f7bb70ff)
$active_border_2  = rgba(dfc2a2ff)
$inactive_border  = rgba(9c8e8055)
$shadow_color     = rgba(00000080)
$shadow_inactive  = rgba(00000040)
