# ╔══════════════════════════════════════════════════╗
# ║  Catppuccin Frappé — Hyprland Colors             ║
# ╚══════════════════════════════════════════════════╝

$active_border_1  = rgb(ca9ee6)
$active_border_2  = rgb(8caaee)
$inactive_border  = rgb(414559)
$shadow_color     = 0xee303446
$shadow_inactive  = 0x66303446

$bg               = rgb(303446)
$surface          = rgb(414559)
$text             = rgb(c6d0f5)
$subtext          = rgb(a5adce)
$primary          = rgb(ca9ee6)
$secondary        = rgb(99d1db)
$green            = rgb(a6d189)
$yellow           = rgb(e5c890)
$red              = rgb(e78284)
$blue             = rgb(8caaee)

$theme_name       = frappe
