# Gerado pelo matugen — não edite manualmente
background  #0e1416
foreground  #dee3e5

selection_background  #83d2e4
selection_foreground  #00363f

cursor            #83d2e4
cursor_text_color #00363f

color0   #0e1416
color1   #ffb4ab
color2   #83d2e4
color3   #bdc5eb
color4   #b2cbd1
color5   #3d4565
color6   #004e5a
color7   #dee3e5
color8   #3f484b
color9   #690005
color10  #00363f
color11  #272f4d
color12  #1c3439
color13  #dce1ff
color14  #a5eeff
color15  #899295
