# Gerado pelo matugen — não edite manualmente
background  #18120c
foreground  #eee0d4

selection_background  #f7bb70
selection_foreground  #462a00

cursor            #f7bb70
cursor_text_color #462a00

color0   #18120c
color1   #ffb4ab
color2   #f7bb70
color3   #bacd9f
color4   #dfc2a2
color5   #3c4c28
color6   #653e00
color7   #eee0d4
color8   #504539
color9   #690005
color10  #462a00
color11  #263514
color12  #3f2d17
color13  #d6e9b9
color14  #ffddb7
color15  #9c8e80
