# Gerado pelo matugen — não edite manualmente
background  #0e1514
foreground  #dde4e3

selection_background  #80d4d5
selection_foreground  #003737

cursor            #80d4d5
cursor_text_color #003737

color0   #0e1514
color1   #ffb4ab
color2   #80d4d5
color3   #b3c8e9
color4   #b0cccb
color5   #344863
color6   #004f50
color7   #dde4e3
color8   #3f4948
color9   #690005
color10  #003737
color11  #1d314b
color12  #1b3435
color13  #d4e3ff
color14  #9cf1f2
color15  #899392
